BOARD_TAG     = uno

ARDMK_DIR     = ~/dev/arduino/arduino-makefile

ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java

AVR_TOOLS_DIR = /usr/local

ARDUINO_PORT  = /dev/tty.usbmodemfa131

PROJECT_DIR = /Users/Ladislas/dev/leka/moti

CURRENT_DIR = $(shell basename $(CURDIR))

include /Users/Ladislas/dev/arduino/arduino-makefile/arduino-mk/Arduino.mk